### ISSUE TITLE
Unhandled Rejection at Promise Error: listen EADDRINUSE: address already in use :::8000

### ISSUE THREAD

**Issue by ajaye2** [tardis-dev/tardis-machine#17]
I am unable to stream data using Tardis-machine when I run:
` tardis-machine --api-key=API_KEY-HERE`

I am getting the following error on EC2:

Unhandled Rejection at Promise Error: listen EADDRINUSE: address already in use :::8000
    at Server.setupListenHandle [as _listen2] (node:net:1463:16)
    at listenInCluster (node:net:1511:12)
    at Server.listen (node:net:1599:7)
    at /home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/dist/tardismachine.js:94:34
    at new Promise (<anonymous>)
    at TardisMachine.start (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/dist/tardismachine.js:91:15)
    at start (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/bin/tardis-machine.js:86:19)
    at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/bin/tardis-machine.js:104:1)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 8000
} Promise {
  <rejected> Error: listen EADDRINUSE: address already in use :::8000
      at Server.setupListenHandle [as _listen2] (node:net:1463:16)
      at listenInCluster (node:net:1511:12)
      at Server.listen (node:net:1599:7)
      at /home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/dist/tardismachine.js:94:34
      at new Promise (<anonymous>)
      at TardisMachine.start (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/dist/tardismachine.js:91:15)
      at start (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/bin/tardis-machine.js:86:19)
      at Object.<anonymous> (/home/ec2-user/.nvm/versions/node/v16.18.0/lib/node_modules/tardis-machine/bin/tardis-machine.js:104:1)
      at Module._compile (node:internal/modules/cjs/loader:1155:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10) {
    code: 'EADDRINUSE',
    errno: -98,
    syscall: 'listen',
    address: '::',
    port: 8000
  }
}

**Comment by thaaddeus** [comment]
You're already have another process running on port 8000 or no rights to use it?

**Comment by ajaye2** [comment]
I currently don't have any other port running, I just launched the ec2 server. Then ran the following in order:

docker run -p 8000:8000 -p 8001:8001 -e "TM_API_KEY=apikey" -d tardisdev/tardis-machine

npx tardis-machine --api-key=apikey
